# Python 08 Creating Functions

[course link](https://swcarpentry.github.io/python-novice-inflammation/)

- duration: 30 mins
- define and call functions

### syntax

``` python
def function_no_return(parameter1, parameter2, ...): 
    ... # do something
    #return None
    
def function_one_return(parameter1, parameter2, ...): 
    ... # do something
    return value

def function_multiple_return(parameter1, parameter2, ...): 
    ... # do something
    return value1, value2, ...
```

In [1]:
### a simple example
def fahr_to_celsius(temp):
    return ((temp - 32) * (5/9))

![python-function](https://swcarpentry.github.io/python-novice-inflammation/fig/python-function.svg)

### question
- what happened after we define a function?
- what did not happen after the defination of a function?

In [2]:
print('freezing point of water:', fahr_to_celsius(32), 'C')
print('boiling point of water:', fahr_to_celsius(212), 'C')

freezing point of water: 0.0 C
boiling point of water: 100.0 C


### example and exercise: Composing Functions

convert temprature units

In [3]:
def celsius_to_kelvin(temp_c):
    return temp_c + 273.15

print('freezing point of water in Kelvin:', celsius_to_kelvin(0.))

freezing point of water in Kelvin: 273.15


write a function to convert Fahrenheit to Kelvin

change the value of num to print out all code branches

In [4]:
def fahr_to_kelvin(temp_f):
    temp_c = fahr_to_celsius(temp_f)
    temp_k = celsius_to_kelvin(temp_c)
    return temp_k

print('boiling point of water in Kelvin:', fahr_to_kelvin(212.0))

boiling point of water in Kelvin: 373.15


test this function with other choices of input parameters

### Variable Scope

In [ ]:
print('Again, temperature in Kelvin was:', temp_k)

In [ ]:
print('Again, temperature in Fahrenheit was:', temp_f)

In [ ]:
print('Again, temperature in Celsius was:', temp_c)

In [ ]:
temp_kelvin = fahr_to_kelvin(212.0)
print('temperature in Kelvin was:', temp_kelvin)

In [ ]:
# can this code block run ?

def print_temperatures():
    print('temperature in Fahrenheit was:', temp_t1_fahr)
    print('temperature in Kelvin was:', temp_t1_kelvin)
    temp_t1_fahr = 0
    temp_t1_kelvin = 5

temp_t1_fahr = 212.0
temp_t1_kelvin = fahr_to_kelvin(temp_t1_fahr)

print_temperatures()

print('temperature in Fahrenheit was:', temp_t1_fahr)
print('temperature in Kelvin was:', temp_t1_kelvin)

In [ ]:
# can this code block run ?

temp_t2_fahr = 212.0
temp_t2_kelvin = fahr_to_kelvin(temp_t2_fahr)

def print_temperatures():
    print('temperature in Fahrenheit was:', temp_t2_fahr)
    print('temperature in Kelvin was:', temp_t2_kelvin)
    temp_t2_fahr = 0
    temp_t2_kelvin = 5

print_temperatures()

print('temperature in Fahrenheit was:', temp_t2_fahr)
print('temperature in Kelvin was:', temp_t2_kelvin)

In [ ]:
# can this code block run ?

def print_temperatures():
    global temp_t3_fahr
    global temp_t3_kelvin
    print('temperature in Fahrenheit was:', temp_t3_fahr)
    print('temperature in Kelvin was:', temp_t3_kelvin)
    temp_t3_fahr = 0
    temp_t3_kelvin = 5

temp_t3_fahr = 212.0
temp_t3_kelvin = fahr_to_kelvin(temp_t3_fahr)

print_temperatures()

print('temperature in Fahrenheit was:', temp_t3_fahr)
print('temperature in Kelvin was:', temp_t3_kelvin)

### example and exercise: Tidying up

In [5]:
import matplotlib
import matplotlib.pyplot

def visualize(filename):
    data = numpy.loadtxt(fname=filename, delimiter=',')

    fig = matplotlib.pyplot.figure(figsize=(10.0, 3.0))

    axes1 = fig.add_subplot(1, 3, 1)
    axes2 = fig.add_subplot(1, 3, 2)
    axes3 = fig.add_subplot(1, 3, 3)

    axes1.set_ylabel('average')
    axes1.plot(numpy.mean(data, axis=0))

    axes2.set_ylabel('max')
    axes2.plot(numpy.max(data, axis=0))

    axes3.set_ylabel('min')
    axes3.plot(numpy.min(data, axis=0))

    fig.tight_layout()
    matplotlib.pyplot.show()

In [6]:
import numpy

def detect_problems(filename):

    data = numpy.loadtxt(fname=filename, delimiter=',')

    if (numpy.max(data, axis=0)[0] == 0) \
        and (numpy.max(data, axis=0)[20] == 20):
        print('Suspicious looking maxima!')
    elif numpy.sum(numpy.min(data, axis=0)) == 0:
        print('Minima add up to zero!')
    else:
        print('Seems OK!')

call the above functions and observe the output

share your code of the function calls

In [ ]:
visualize('data/inflammation-01.csv')

In [ ]:
detect_problems('data/inflammation-01.csv')

### Testing and Documenting

> why do we need Testing and Documenting functions?

> how many tests did we do for temperature conversion?

In [ ]:
# example of documenting
import numpy
help(numpy.loadtxt)

> what are the key elements in function documentation ?

In [7]:
def offset_mean(data, target_mean_value):
    return (data - numpy.mean(data)) + target_mean_value

- how to properly test this function ?
- how to properly document this function ?

write good tests

- typical inputs and outputs
- zeros (anomaly)
- [mathematical induction](https://en.wikipedia.org/wiki/Mathematical_induction)

In [8]:
import numpy
z = numpy.zeros((2,2))
print(offset_mean(z, 3))

[[3. 3.]
 [3. 3.]]


In [9]:
z2 = numpy.random.normal(3, 5, 8)
offset_mean_z2 = offset_mean(z2, 10)
print(z2, z2.mean())
print(offset_mean_z2, offset_mean_z2.mean())

[ 7.37197482  4.53046699  1.65815119  8.34885875  9.88557394 -0.19459353
  2.1489854   1.51151754] 4.407616888715739
[12.96435794 10.12285011  7.25053431 13.94124186 15.47795705  5.39778958
  7.74136851  7.10390065] 10.0


In [10]:
data = numpy.loadtxt(fname='data/inflammation-01.csv', delimiter=',')
print('mean of data', data.mean())
offset_data = offset_mean(data, 10)
print('mean of offset data', offset_data.mean())

mean of data 6.14875
mean of offset data 10.0


observe and compare the values in data and offset_data

> share your code of the comparison

In [11]:
print(data[0:3, 0:3])
print(offset_data[0:3, 0:3])

[[0. 0. 1.]
 [0. 1. 2.]
 [0. 1. 1.]]
[[3.85125 3.85125 4.85125]
 [3.85125 4.85125 5.85125]
 [3.85125 4.85125 4.85125]]


> how to document a function

- write comments ?
- write docstring

In [12]:
def offset_mean(data, target_mean_value):
    """Return a new array containing the original data
       with its mean offset to match the desired value.

    Examples
    --------
    >>> offset_mean([1, 2, 3], 0)
    array([-1.,  0.,  1.])
    """
    return (data - numpy.mean(data)) + target_mean_value

help(offset_mean)

Help on function offset_mean in module __main__:

offset_mean(data, target_mean_value)
    Return a new array containing the original data
       with its mean offset to match the desired value.
    
    Examples
    --------
    >>> offset_mean([1, 2, 3], 0)
    array([-1.,  0.,  1.])



> Python’s built-in help system

### Defining Defaults

Default input parameters

- observe `Parameters` in `help(numpy.loadtxt)`
- compare the difference between `fname` and `delimiter`

example

- fname : file, str, pathlib.Path, list of str, generator
        File, filename, list, or generator to read.  If the filename
        extension is ``.gz`` or ``.bz2``, the file is first decompressed. Note
        that generators must return bytes or strings. The strings
        in a list or produced by a generator are treated as lines.

- delimiter : str, optional
        The string used to separate values. For backwards compatibility, byte
        strings will be decoded as 'latin1'. The default is whitespace.

test with `numpy.loadtxt`

In [13]:
numpy.loadtxt('data/inflammation-01.csv', delimiter=',')

array([[0., 0., 1., ..., 3., 0., 0.],
       [0., 1., 2., ..., 1., 0., 1.],
       [0., 1., 1., ..., 2., 1., 1.],
       ...,
       [0., 1., 1., ..., 1., 1., 1.],
       [0., 0., 0., ..., 0., 2., 0.],
       [0., 0., 1., ..., 1., 1., 0.]])

In [14]:
numpy.loadtxt('data/inflammation-01.csv', ',')

SyntaxError: unexpected EOF while parsing (<unknown>, line 1)

how to define a function that takes default parameter values

In [15]:
def offset_mean(data, target_mean_value=0.0):
    """Return a new array containing the original data
       with its mean offset to match the desired value, (0 by default).

    Examples
    --------
    >>> offset_mean([1, 2, 3])
    array([-1.,  0.,  1.])
    """
    return (data - numpy.mean(data)) + target_mean_value

test_data = numpy.zeros((2, 2))
print(offset_mean(test_data, 3))

[[3. 3.]
 [3. 3.]]


In [16]:
def display(a=1, b=2, c=3):
    print('a:', a, 'b:', b, 'c:', c)

print('no parameters:')
display()
print('one parameter:')
display(55)
print('two parameters:')
display(55, 66)

no parameters:
a: 1 b: 2 c: 3
one parameter:
a: 55 b: 2 c: 3
two parameters:
a: 55 b: 66 c: 3


In [17]:
print('only setting the value of c')
display(c=77)

only setting the value of c
a: 1 b: 2 c: 77


In [ ]:
import matplotlib.pyplot as plt
help(plt.plot)

In [18]:
def print_a_list(*args):
    print('-----'*10)
    for item in args:
        print(item)
    print('-----'*10)

print_a_list(1,2,3)
print_a_list(1,2,3,4,5,6,7)

--------------------------------------------------
1
2
3
--------------------------------------------------
--------------------------------------------------
1
2
3
4
5
6
7
--------------------------------------------------


In [19]:
def print_a_list(**kwargs):
    print('-----'*10)
    for key in kwargs:
        print(key, kwargs[key])
    print('-----'*10)

print_a_list(this=1, that=2)
print_a_list(x=1,y=2,z=3)

--------------------------------------------------
this 1
that 2
--------------------------------------------------
--------------------------------------------------
x 1
y 2
z 3
--------------------------------------------------


### exercise: Selecting Characters From Strings

If the variable `s` refers to a string, then `s[0]` is the string’s first character and `s[-1]` is its last. Write a function called `outer` that returns a string made up of just the first and last characters of its input. A call to your function should look like this:

``` python
# given a function call of outer
print(outer('helium'))
# should output hm
```

In [20]:
def outer(input_string):
    return input_string[0] + input_string[-1]

# given a function call of outer
print(outer('helium'))
# should output hm

hm


### exercise: Rescaling an Array

Write a function `rescale` that takes an array as input and returns a corresponding array of values scaled to lie in the range 0.0 to 1.0. (Hint: If `L` and `H` are the lowest and highest values in the original array, then the replacement for a value `v` should be `(v-L) / (H-L)`.)

In [21]:
def rescale(input_array):
    """Takes an array as input, and returns a corresponding array 
    scaled so that 0 corresponds to the minimum and 1 to 
    the maximum value of the input array.

    Examples:
    >>> rescale(numpy.arange(10.0))
    array([ 0.        ,  0.11111111,  0.22222222,  0.33333333,  
            0.44444444,
           0.55555556,  0.66666667,  0.77777778,  0.88888889,  
           1.        ])
    >>> rescale(numpy.linspace(0, 100, 5))
    array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])
    """
    L = numpy.min(input_array)
    H = numpy.max(input_array)
    output_array = (input_array - L) / (H - L)
    return output_array

In [22]:
help(rescale)

Help on function rescale in module __main__:

rescale(input_array)
    Takes an array as input, and returns a corresponding array 
    scaled so that 0 corresponds to the minimum and 1 to 
    the maximum value of the input array.
    
    Examples:
    >>> rescale(numpy.arange(10.0))
    array([ 0.        ,  0.11111111,  0.22222222,  0.33333333,  
            0.44444444,
           0.55555556,  0.66666667,  0.77777778,  0.88888889,  
           1.        ])
    >>> rescale(numpy.linspace(0, 100, 5))
    array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ])



### exercise: Variables Inside and Outside Functions

What does the following piece of code display when run — and why?

In [23]:
f = 0
k = 0

def f2k(f):
    k = ((f - 32) * (5.0 / 9.0)) + 273.15
    return k

print(f2k(8))
print(f2k(41))
print(f2k(32))

print(k)

259.81666666666666
278.15
273.15
0


### exercise: Mixing Default and Non-Default Parameters

In [24]:
def numbers(one, two=2, three, four=4):
    n = str(one) + str(two) + str(three) + str(four)
    return n

print(numbers(1, three=3))

SyntaxError: non-default argument follows default argument (2203058596.py, line 1)